[package]
name = "ont2bisul"
version = "0.1.0"
links = "fast5"
build = "build.rs"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }

[dependencies]
libc = "*"
rust-htslib = "0.38.2"
bio-types = "0.12.0"
